//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prg_Portfolio.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Price()
        {
            this.Tbl_Price_Products = new HashSet<Tbl_Price_Products>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public Nullable<System.DateTime> DeactivationDateTime { get; set; }
        public Nullable<int> Deactivetor_Id { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
        public Nullable<int> Modificator_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Price_Products> Tbl_Price_Products { get; set; }
    }
}
