//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prg_Portfolio.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CommentProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_CommentProduct()
        {
            this.Tbl_CommentProduct1 = new HashSet<Tbl_CommentProduct>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Products_Id { get; set; }
        public Nullable<byte> ReasonRating_Id { get; set; }
        public string Text { get; set; }
        public string Email { get; set; }
        public Nullable<long> RepllayTo { get; set; }
        public Nullable<byte> Point_Of100 { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public Nullable<System.DateTime> DeactivationDateTime { get; set; }
        public Nullable<int> Deactivetor_Id { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
        public Nullable<int> Modificator_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> User_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CommentProduct> Tbl_CommentProduct1 { get; set; }
        public virtual Tbl_CommentProduct Tbl_CommentProduct2 { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
        public virtual Tbl_ReasonRating Tbl_ReasonRating { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
