//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prg_Portfolio.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BuyFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BuyFactor()
        {
            this.Tbl_BuyFactorDetail = new HashSet<Tbl_BuyFactorDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Salesman_Id { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> PayPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> GetDate { get; set; }
        public Nullable<int> FactorNumber { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public Nullable<System.DateTime> DeactivationDateTime { get; set; }
        public Nullable<int> Deactivetor_Id { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
        public Nullable<int> Modificator_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Tbl_Salseman Tbl_Salseman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BuyFactorDetail> Tbl_BuyFactorDetail { get; set; }
    }
}
