//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prg_Portfolio.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Blog()
        {
            this.Tbl_CommentBlog = new HashSet<Tbl_CommentBlog>();
            this.Tbl_Blog_Picture = new HashSet<Tbl_Blog_Picture>();
            this.Tbl_Blog_Tag = new HashSet<Tbl_Blog_Tag>();
        }
    
        public long Id { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<int> Creator_Id { get; set; }
        public Nullable<System.DateTime> DeactivationDateTime { get; set; }
        public Nullable<int> Deactivetor_Id { get; set; }
        public Nullable<System.DateTime> ModificationDateTime { get; set; }
        public Nullable<int> Modificator_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ViewBlog_Count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CommentBlog> Tbl_CommentBlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Blog_Picture> Tbl_Blog_Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Blog_Tag> Tbl_Blog_Tag { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
